import Header from '../../components/ClientNavigator'
import EnterpriseSidebar from '../../components/EnterpriseSidebar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header /> {/* 모든 페이지에 Header 포함 */}
        <div className="flex">
        <EnterpriseSidebar/>
        {children}{/* 페이지 콘텐츠 */}
        </div>
      </body>
    </html>
  );
}
