import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './global.css'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-noto-sans-kr',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.className} antialiased`}>{children}</body>
      <Toaster />
    </html>
  )
}
