import type { Metadata } from 'next'
import { Noto_Sans_KR, Inter } from 'next/font/google'
import Header from '@/layout/Header'
import './globals.css'
import GlobalNavigator from '@/components/GlobalNavigator'
import AccountProvider from './_providers/AccountProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-noto-sans-kr',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.className} antialiased`}>
        <AccountProvider />
        <GlobalNavigator />
        <Header />
        <main className="flex w-full h-full min-h-[calc(100vh-96px)] pt-1">
          <div className="flex mx-auto w-full max-w-[1024px] ">{children}</div>
        </main>
      </body>
    </html>
  )
}
